### ISSUE TITLE
Check wasm-genesis-flags in genesis validation and fail fast

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#114]
We should be able to validate the genesis and fail fast before starting the chain

* set-privileged : check contract exists
* set-pinned: check that code_id exists

There is some complexity with genesis messages that needs to be taken into account.

**Comment by daniellarita** [comment]
@pinosu can you check if this is complete?

**Comment by pinosu** [comment]
Closing because it was implemented as part of #61
