### ISSUE TITLE
Support Staking/Distribution CosmosMsgs

### ISSUE THREAD

**Issue by ethanfrey** [confio/tgrade#161]
We already support adaptors for external queries/messages for staking/distribution.

We should support CosmosMsg::Staking and CosmosMsg::Distribution in the same way. (messages returned from contract execute)

We allow self-staking and have a distribution contract now for validators.

It doesn't matter about client (cli/grpc) messages/queries for this, only about internal contract calls. This means being able to handle the [following messages](https://github.com/CosmWasm/wasmvm/blob/v0.16.0/types/msg.go#L177-L216) and [following queries](https://github.com/CosmWasm/wasmvm/blob/main/types/queries.go#L206-L327)

**Comment by daniellarita** [comment]
@alpe is this still relevant?

**Comment by alpe** [comment]
This is covered by doc now. People on mainnet are familiar with the PoE CLI commands
