### ISSUE TITLE
Support staking queries

### ISSUE THREAD

**Issue by ethanfrey** [confio/tgrade#162]
Ensure all metadata is in the contracts.
Provide adaptor for the gRPC clients.
Ensure we have all info needed for CosmWasm query request support as well

Builds on https://github.com/confio/tgrade-contracts/issues/280 Please comment there for any other info needed by the sdk. Especially for slashing/jailing.

Update:
This task is about implementing a new [StakingQuerier](https://github.com/CosmWasm/wasmd/blob/v0.27.0/x/wasm/keeper/query_plugins.go#L277) query handlers that works with PoE contracts, so that contracts can query data using the same query api.
Some queries are implemented already in https://github.com/confio/tgrade/blob/main/x/poe/wasm/query_plugin.go#L25

**Comment by daniellarita** [comment]
@alpe can you see if this is still relevant

**Comment by pinosu** [comment]
Closing the issue because it is already implemented.
