### ISSUE TITLE
Add more fraud scenario tests

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#197]
Follow on https://github.com/confio/tgrade/pull/180#pullrequestreview-804829481
Test
- [x] recursive query loop (contract A calls QuerySmart on itself, which calls QuerySmart on itself....) each instance takes up some memory and all are on the call stack at once. TODO Alex: link to hackatom contract

Can be implemented in wasmd

**Comment by daniellarita** [comment]
was this already completed on 29/11?

**Comment by alpe** [comment]
ja, there is a recurse smart query test indeed
