### ISSUE TITLE
Fix flaky system tests  on CI

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#218]
They work fine on my box but randomly fail on CI.
https://app.circleci.com/pipelines/github/confio/tgrade/533/workflows/efc0cd0a-c6cc-4ae9-b4b0-eb9df5b89337/jobs/2002

Try sleep 5-10 seconds before starting nodes for example.

**Comment by alpe** [comment]
I had to solve some issues with system tests in #233 . `node4` home dir was not removed proper.
I would keep this issue open for some more days to see if that was the root issue

**Comment by BirgitPohl** [comment]
How many times is this failing?
Often, less often?

**Comment by daniellarita** [comment]
Let's track how often they are failing and see how necessary it is to fix them
