### ISSUE TITLE
Ensure Cosmos-SDK vesting accounts work with PoE

### ISSUE THREAD

**Issue by ethanfrey** [confio/tgrade#220]
After discussion with validators, we will use standard cosmos-sdk vesting accounts for them. We must ensure this works and test this in the 0.6 testnet.

1. Example how to create such a vesting account in genesis
2. Ensure such account can stake/unstake tokens to the PoE contract
3. Ensure there is a simple command line tool to do so, eg. `tgrade tx stake ...`
4. Ensure given account cannot send via bank, nor send tokens to contracts (Wasm/Execute,Instantiate,etc)

Questions:

* Do vesting accounts explicitly enable staking module? Or explicitly disable bank module? (This has implications for using with wasm)
* Do we need to pay fees in gentx? (eg global fee module)
* Can a vesting account cover fees with the still-vesting tokens (likely not, but let's check)?
* based on above, how to we make genesis vesting that can cover gentx to stake

**Comment by ethanfrey** [comment]
Looking at the Cosmos SDK a bit, it seems the bank has a separate call to delegate coins (rather than send/burn) that allows the use of vesting tokens: https://github.com/cosmos/cosmos-sdk/blob/c14b101a7a3ea6b126261a9e2d7b9a937140ceba/x/bank/keeper/keeper.go#L112-L118

We will likely need to modify this somehow (using staking adaptor?) to accept the poe staking via delegate

**Comment by alpe** [comment]
There is some good [doc](https://docs.cosmos.network/v0.42/modules/auth/05_vesting.html) .

**Comment by ethanfrey** [comment]
Kind of... it explains the account itself, not the interaction with bank: 
https://docs.cosmos.network/v0.42/modules/auth/05_vesting.html#delegating refers to "upstream caller" which would be bank I think.

So basically, we need to look at bank.

**Comment by alpe** [comment]
I have a spiked a solution that we can discuss.

**Comment by alpe** [comment]
> Do vesting accounts explicitly enable staking module? Or explicitly disable bank module? (This has implications for using with wasm)

We discussed this already. Both modules work together. Staking module is not using default bank send but a delegate/ undelegate method

> Do we need to pay fees in gentx? (eg global fee module)

With the global fee module enabled, Yes

> Can a vesting account cover fees with the still-vesting tokens (likely not, but let's check)?

No, tx fails with `insufficient funds`

> based on above, how to we make genesis vesting that can cover gentx to stake

The the total balance amount needs to be > vesting amount so that some liquid tokens are available. For example:
`tgrade add-genesis-account tgrade1... 200000000utgd --vesting-amount=100000000utgd ...`

**Comment by ethanfrey** [comment]
Great work and report back.

I think this issue can be closed. It would be great to make the above comment more findable

**Comment by alpe** [comment]
Update:
> based on above, how to we make genesis vesting that can cover gentx to stake

Sorry, I modified the system test to confirm the fees are working but commented before testing with genTx. When I tried this now with /contrib/local/ scripts then the account has no liquid tokens during gentx executen phase to pay the fees.  Need to 👀

**Comment by alpe** [comment]
ok found the issue. and can confirm now it works as described earlier.  😅 
https://github.com/confio/tgrade/blob/220_vesting-create-validator/contrib/local/setup_tgrade.sh#L53

**Comment by alpe** [comment]
Left to do: 
- [ ] https://github.com/confio/poe-contracts/pull/124
- [ ] https://github.com/confio/tgrade/issues/234

**Comment by alpe** [comment]
All done on the backend side
