### ISSUE TITLE
Initialize OC in genesis

### ISSUE THREAD

**Issue by ethanfrey** [confio/tgrade#221]
After discussion with Martin, we decided that for both OC (Oversight Community) and AP (Arbiter Pool), we will already know off-chain the identities of the genesis participants and have their consent for initial setup. This means we can take a list of members in the genesis file and set it up during `InitGenesis` call. The process will be:

Validate:
* Ensure all accounts in the initial list have a bank balance of more than "escrow_amount" `utgd`

Execute:

* Create Trusted-Circle (OC or AP) using the first member of the member list as creator, and sending the min escrow. (Replace "systemAdmin" as creator [2nd param](https://github.com/confio/tgrade/blob/v0.6.2/x/poe/bootstrap.go#L92))
* Creator makes a proposal to add **all other members** ( example for a gov [proposal](https://github.com/confio/tgrade/blob/v0.6.2/x/poe/contract/tgrade_oc_proposals_integration_test.go#L45) )
* Create executes this proposal  ([example](https://github.com/confio/tgrade/blob/v0.6.2/x/poe/contract/tgrade_oc_proposals_integration_test.go#L54))
* Loop over all other members, call `DepositEscrow` with the minimum amount
* Check the voting member set is equal to the list of all members defined in genesis (Example: https://github.com/confio/tgrade/blob/v0.6.2/x/poe/contract/tgrade_oc_proposals_integration_test.go#L31))

All these calls can be done in Go and is the only way to send tokens from many accounts to a contract.
Edge case to test:
- OC member has not enough tokens for deposit
- Ensure number of members is >0

**Comment by ethanfrey** [comment]
Another useful test case to base on in Rust https://github.com/confio/tgrade-contracts/blob/main/contracts/tgrade-trusted-circle/src/tests/bdd_tests.rs#L116-L141

The relevant Go code is here https://github.com/confio/tgrade/blob/main/x/poe/bootstrap.go#L84-L95 which just creates with one member. We need to add a function to proposal all the other voters and have each deposit their escrow one by one (just as in the Rust code from unit test setup)

**Comment by alpe** [comment]
@kmw101 can we safely assume and check that all OC members have enough tokens to pay the escrow?

**Comment by kmw101** [comment]
> @kmw101 can we safely assume and check that all OC members have enough tokens to pay the escrow?

We will allocate tokens in Genesis to OC members.
