### ISSUE TITLE
Update to tgrade-contracts with AP

### ISSUE THREAD

**Issue by ethanfrey** [confio/tgrade#224]
Whatever version/tag that is.

Depends on https://github.com/confio/tgrade-contracts/issues/417 and a version tag

**Comment by maurolacy** [comment]
This is now depending only on a version tag:
 - https://github.com/confio/poe-contracts/pull/135
 - https://github.com/confio/tgrade-contracts/issues/488

**Comment by alpe** [comment]
This was done
