### ISSUE TITLE
Set denom metadata in genesis

### ISSUE THREAD

**Issue by webmaster128** [confio/tgrade#229]
We have no denomMetadata set for our networks (tested tgrade-testbnet-3). We should do that as clients will start using that soonish and the upcoming sign mode textual will depend on it.

Example entry here: https://github.com/cosmos/cosmjs/blob/c192fc9b95ef97e4afbf7f5b94f8e8194ae428a6/scripts/simapp44/template/.simapp/config/genesis.json#L438-L456

It's still a bit unclear to me if the display denom is supposed to be upper case on chain as users expect it in UIs. Brought this up here: https://github.com/cosmos/cosmos-sdk/pull/10701#discussion_r781364286

**Comment by ethanfrey** [comment]
Very good point and thanks for bringing this up.

Also related to the discussion here: https://github.com/CosmWasm/wasmd/issues/671 which will need metadata as well.
(Not the same code, but the same concepts)

**Comment by alpe** [comment]
I have added a template in the PR with lower case letters, following the example in https://docs.cosmos.network/master/architecture/adr-024-coin-metadata.html

For any testnet genesis we may want to modify the description or other values. // fyi: @migmeneses

**Comment by alpe** [comment]
done
