### ISSUE TITLE
Decide on max_wasm_code_size

### ISSUE THREAD

**Issue by webmaster128** [confio/tgrade#239]
Traditionally we used 600 KiB which was changed to 1200 KiB in https://github.com/CosmWasm/wasmd/pull/550. I am not aware of any testing or analysis what the implications of this new value is. It now made it into Tgrade.

I think we should double check if 1200 KiB is really the value we want to offer in the first version of Tgrade. Those magabytes we will have to carry around for a long time and it will be very hard to decrease the limit later on.

Terra is talking about increasing the limit from 600 -> 1200 but the arguments don't seem to be very convincing on both sides:
- https://station.terra.money/proposal/179
- https://agora.terra.money/t/increase-the-wasm-code-size-in-terra-blockchain/3472
- https://twitter.com/SmartStake/status/1484556009842659329

**Comment by daniellarita** [comment]
@webmaster128 @migmeneses do you have some final opinions on what size we should use?

**Comment by webmaster128** [comment]
Let's use 777 KiB until we have a better clue.

**Comment by migmeneses** [comment]
dryrunnet has max_wasm_code_size of:
"max_wasm_code_size": "1228800"

**Comment by webmaster128** [comment]
I would stay well below 1MB as this is not needed right now and sinces above 600-800KB are not well tested.

**Comment by webmaster128** [comment]
Looking at the changes in https://github.com/CosmWasm/wasmd/pull/826, I suggest using the default from wasmd unless we have a very good reason to change it. The value is not needed in genesis anymore.

**Comment by alpe** [comment]
I was about to suggest the same. I will close this now
