### ISSUE TITLE
Ensure tgrade cli binary supports ledger

### ISSUE THREAD

**Issue by ethanfrey** [confio/tgrade#241]
## Acceptance Criteria
- users should be able to sign CLI transactions with their ledger
- document the compile flag in Slab: (LEDGER_ENABLED=true)

------
People should be able to sign cli transactions with their ledger.

It should work. Someone needs to test and possibly document a compile flag (LEDGER_ENABLED=true)

**Comment by alpe** [comment]
Ledger support is enabled by default in our [Makefile](https://github.com/confio/tgrade/blob/main/Makefile#L6)

I have tested successfully:
* `tgrade keys add myledger --ledger`
* ` tgrade tx  bank send $myAccount $otherAccount 100000utgd  --ledger --node=https://rpc.patchnet-1.tgrade.io:443 --chain-id=tgrade-patchnet-1 --fees=10000utgd`
* `tgrade tx wasm instantiate "$CODE_ID" "$INIT" --admin="$(tgrade keys show myledger -a)" main 7446e8d
  --from myledger --amount="100utgd" --label "local0.1.0"  --gas 1000000 -y --chain-id=tgrade-patchnet-1 -b block -o json --ledger --fees=100000utgd --node=https://rpc.patchnet-1.tgrade.io:443`
* `tgrade tx poe create-validator
	--amount 1000utgd
	--from myledger
	--pubkey '{"@type":"/cosmos.crypto.ed25519.PubKey","key":"SPDo3zactZ83pOm3tVvZUntwiYXJeO9f4j1feE3SfU8="}'
	--chain-id=tgrade-patchnet-1
    --moniker="delme"
    --node=https://rpc.patchnet-1.tgrade.io:443
    --fees=50000utgd --ledger
`
  
Failed:
*`tgrade tx wasm store ./testing/contract/hackatom.wasm.gzip --from myledger --gas 1500000 -y --chain-id=tgrade-patchnet-1 --node=https://rpc.patchnet-1.tgrade.io:443 -b block -o json --ledger`
> Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.
Error: [APDU_CODE_OUTPUT_BUFFER_TOO_SMALL] Authentication method blocked

**Comment by alpe** [comment]
Assigned Pino to test with his new ledger as well

**Comment by ethanfrey** [comment]
The `tx wasm store` is a know limitation of wasmd in general (and ledger).
I have always used some local account to store. I send a few tokens for gas and it has no permissions, so this is fine. It is often important to instantiate with a secure ledger account
