### ISSUE TITLE
Smoke test suite via cli

### ISSUE THREAD

**Issue by ethanfrey** [confio/tgrade#273]
Some scripts to get more confidence on the live testnets. Examples:

* Upload contracts
* Stake/unstake validators

Not stuff that is triggered by the app ui (that can be tested manually?)

Try it out on internal-8

**Comment by alpe** [comment]
These bash scripts can be a start https://github.com/CosmWasm/wasmd/tree/master/contrib/local

**Comment by migmeneses** [comment]
Hi @alpe and @ethanfrey 
I just filled a new Issue in IaC:
https://github.com/confio/IaC/issues/1

Basically, I will spin up a machine that will do multiple cronjob and tests
No idea how to call it.
I was thinking:
`operations-machine`

**Comment by alpe** [comment]
Splitting into 2 tasks:
- manual run against internal-8
- automated process for all new networks [@migmeneses ](https://github.com/confio/IaC/issues/1)

**Comment by migmeneses** [comment]
OK, I am using the script by @alpe 
It is now located on:
Machine: `operations-machine`
Public IP: `188.34.183.90`
directory `/opt`

It is a symbolic link and it works pretty well:
```root@operations-machine:/opt# ls -l
total 8
drwxr-xr-x 4 root root 4096 Feb 15 14:30 cliff-snapshot-as-backup
drwxr-xr-x 4 root root 4096 Feb 21 09:09 internal-9-snapshot-as-backup
lrwxrwxrwx 1 root root   34 Feb 24 15:14 smoke-test -> /home/miguel/tgrade/contrib/local/
```

**Comment by migmeneses** [comment]
Pending:
- Documentation in Slab

**Comment by migmeneses** [comment]
operations-machine:
https://confio.slab.com/posts/operations-machine-pkipxwn5

smoke-test:
https://confio.slab.com/posts/smoke-test-fuyudm2q

**Comment by alpe** [comment]
The doc points to a branch in tgrade. If the testsuite makes sense then I can bring it to the main branch. 
Note: the suite contains endpoints and chain-id hard coded to patchnet.

**Comment by alpe** [comment]
This is the link to the branch: https://github.com/confio/tgrade/tree/smoke_tests

**Comment by migmeneses** [comment]
Hi @alpe 
Yes, the symbolic link is point to:
```smoke-test -> /home/miguel/tgrade/contrib/local/```
and I know this is a branch.
Should we merge such branch on the remote/origin repo?

**Comment by maurolacy** [comment]
Will try to put this in good shape for merging to main.

**Comment by maurolacy** [comment]
To be closed by https://github.com/confio/tgrade-testnets/pull/64.
