### ISSUE TITLE
Remove evidence module

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#332]
The PoE module takes care about evidences in the begin blocker. This task is about checking where/ how it is used for manual msg submission and  removing the evidence module from the app.go when it is unused
// @ethanfrey  WDYT?

**Comment by ethanfrey** [comment]
Good point. I have no idea how manual submission works. Does it evaluate it in sdk and then call into begin block from tendermint???

Maybe there is a special tendermint command for this?

If you could link relevant info and the decision you made or your reasoning, I can review it and let you know if I agree

**Comment by daniellarita** [comment]
Is this critical for mainnet mvp?

**Comment by alpe** [comment]
I have looked deeper into the sdk code. The evidence module has 
* an [abci component](https://github.com/cosmos/cosmos-sdk/blob/v0.45.4/x/evidence/abci.go#L17) to read byzantine validators on begin block. We do the same in the [poe valset contract](https://github.com/confio/poe-contracts/blob/main/contracts/tgrade-valset/src/contract.rs#L1018)
* a [MsgSubmitEvidence](https://github.com/cosmos/cosmos-sdk/blob/v0.45.4/proto/cosmos/evidence/v1beta1/tx.proto#L15) to manually submit evidence data. Though this only works with a [router](https://github.com/cosmos/cosmos-sdk/blob/v0.45.4/x/evidence/keeper/keeper.go#L82) that is never set in [app.go](https://github.com/confio/tgrade/blob/v0.10.0-rc1/app/app.go#L362-L369) . Neither it is in [simd](https://github.com/cosmos/cosmos-sdk/blob/v0.45.4/simapp/app.go#L290-L295) or [gaia](https://github.com/cosmos/gaia/blob/v7.0.2/app/app.go) . The missing router causes a panic with is handled downstream and results in failing the tx

As we have PoE handling bytzantine validators, it is safe to remove the evidence module.
