### ISSUE TITLE
Define mainnet PoE function

### ISSUE THREAD

**Issue by maurolacy** [confio/tgrade#354]
The tg4-mixer PoE function is currently set as `GeometricMean`:https://github.com/confio/tgrade/blob/8a081cbb0d8b0c62bdda58a293058498829095d7/x/poe/bootstrap.go#L140-L150

This is good for testing, but does not reflect the sigmoid-like PoE mixing behaviour of engagement points and staking amounts.

Let's change this to `Sigmoid { r_max: 1000, p: 0.68, s: 0.00003}`, the function and proposed settings in the [PoE white paper](https://github.com/confio/ProofOfEngagement/blob/master/Proof%20of%20Engagement%20paper.pdf).

Alternatively, a `SigmoidSqrt { r_max: 1000, s: 0.0003}` could be used for performance reasons. At the expense of some lack of saturation at the `r_max` levels.

See https://github.com/confio/poe-contracts/blob/main/contracts/tg4-mixer/benches/main.rs for benchmarks / details.

**Comment by alpe** [comment]
Should this task go into PoE-contracts repo instead?

**Comment by maurolacy** [comment]
No, because this is an instantiation param of the tg4-mixer contract, set during bootstrap.

**Comment by daniellarita** [comment]
@maurolacy is this task critical for Mainnet MVP?

**Comment by maurolacy** [comment]
I think this is not critical, but important. This is a small task, just changing the PoE function setup in the mixer contract bootstrap / instantiation, and adapt tests.
