### ISSUE TITLE
Upgrade PoE contracts to release version

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#377]
Placeholder until the final version is defined

Version should include: https://github.com/confio/poe-contracts/issues/139

**Comment by maurolacy** [comment]
Released [poe-contracts 0.10.0](https://github.com/confio/poe-contracts/releases/tag/v0.10.0 )and [tgrade-contracts 0.10.0](https://github.com/confio/tgrade-contracts/releases/tag/v0.10.0).

Leaving this open as other versions are probably to be needed.

**Comment by alpe** [comment]
Adding the blocked label as we can not complete this until the final contract versions are tagged

**Comment by ethanfrey** [comment]
They seem to be tagged now, I will review #398 shortly
