### ISSUE TITLE
Implement "validator_votes" query for valset contract

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#388]
As discussed on slack the votes on begin_block can be "stored" in memory for the current block only.

Steps:
- Collect votes from `RequestBeginBlock.LastCommitInfo` in [poe/abci.go](https://github.com/confio/tgrade/blob/main/x/poe/abci.go#L55)  and keep them in memory.
- implement custom tgrade query for [valset](https://github.com/confio/poe-contracts/blob/v0.11.0/contracts/tgrade-valset/src/contract.rs#L679-L684)

**Comment by daniellarita** [comment]
@maurolacy will create contract related ticket for this and link it here. Thanks

**Comment by maurolacy** [comment]
The relevant issue in poe-contracts is https://github.com/confio/poe-contracts/issues/149.
