### ISSUE TITLE
Keep supporting seed mode?

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#447]
Now that the chain is running and some contracts were upgraded already, we need to discuss how to keep up with the changes.
The repo does not contain the new contract binaries as we are not running in seed mode anymore.
For new testnets though this is different. Do we want to provide automated migrations on startup for example to be compatible with the original mainnet genesis or do we store the latest contract releases only?

**Comment by abefernan** [comment]
To me the ideal scenario would be:
- For testnets do the same steps as for mainnet, to make sure that flow works with contract migration.
- For local docker automatically get the latest version of the contracts.

**Comment by daniellarita** [comment]
is this the ticket that you need in order to unblock your arbiter pool work @abefernan ?

**Comment by abefernan** [comment]
> is this the ticket that you need in order to unblock your arbiter pool work @abefernan ?

Yes

**Comment by pinosu** [comment]
How do we want to proceed with this? the 3 alternatives discussed until now are:

- having the latest contracts on main branch 
- having a separate branch for this
- having a separate repo for this

please let me know if you have other ideas.

**Comment by daniellarita** [comment]
Since you have unblocked Abel another way can we remove this from the sprint @pinosu ?

**Comment by pinosu** [comment]
No at the end this was the best option. Here is the pr https://github.com/confio/tgrade/pull/456 . Once this is merged, I will tag the release and Abel can continue his work.

**Comment by pinosu** [comment]
Decision was to store latest contract releases.
