### ISSUE TITLE
Add support for Automated payment of OC/AP members

### ISSUE THREAD

**Issue by pinosu** [confio/tgrade#452]
Implement blockchain part related to tc-payments contract.

TODOs:

1. Store and instantiate this contract in the chain. That means, a contract "upgrade" proposal for tc-payments.
2. Modify tgrade so that it calls this contract's end blocker. That means, a tgrade chain upgrade proposal.
3. Modify valset distribution so that it sends the engagement funds to this contract instead to the engagement contract. That means, a valset contract upgrade proposal, as the distribution list is currently not part of the update config mechanism (https://github.com/confio/poe-contracts/issues/182).

**Comment by ueco-jb** [comment]
Release 0.14 of tgrade-contracts is required beforehand.

**Comment by alpe** [comment]
> Modify tgrade so that it calls this contract's end blocker. That means, a tgrade chain upgrade proposal.
No need to upgrade the chain. When when.a contract is promoted to "privileged" (via gov proposal), a callback to the contract is sent to let it register for chain permissions (end blocker in this case).

**Comment by maurolacy** [comment]
> > Modify tgrade so that it calls this contract's end blocker. That means, a tgrade chain upgrade proposal.
> 
> No need to upgrade the chain. When when.a contract is promoted to "privileged" (via gov proposal), a callback to the contract is sent to let it register for chain permissions (end blocker in this case).

Nice! Didn't knew that.

> 
> > Release 0.14 of tgrade-contracts
> 
> The repo was tagged 3 days ago. ( https://github.com/confio/poe-contracts/releases/tag/v0.14.0) do you mean v0.15 ?

tc_payments is part of tgrade-contracts, not poe-contracts. This requires a new release of tgrade-contracts, yes. I can do it.

**Comment by maurolacy** [comment]
The only problem is that that gov proposal is currently unimplemented at the voting contract level (https://github.com/confio/poe-contracts/issues/158).

Will implement that, and we would finally have a route for storing, instantiating, promoting and wiring the payments contract.

**Comment by daniellarita** [comment]
Ok thanks. So it looks like there isn't anything that needs to be done on the blockchain side. 

@maurolacy have you had a chance to implement PromoteToPrivilegedContract?

**Comment by maurolacy** [comment]
Yes, this is already done (see https://github.com/confio/poe-contracts/pull/188).

In fact the validator-voting contract with these changes is already deployed and migrated. See proposal #8 in [tgrade mainnet](https://dapp.tgrade.finance/validators).

**Comment by maurolacy** [comment]
See the following slab doc for detailed progress / data for this: https://confio.slab.com/posts/tgrade-tc-payments-deployment-on-mainnet-j8k6iz27.
