### ISSUE TITLE
Epic: PoE module follow ups

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#53]
## Incomplete
~~* Genesis elements to customize the PoE contract instantiation config (fix in code)~~
~~* Queries (CLI/GRPC) that bridge to the PoE contracts~~

## Missing
* Export genesis via state dump
* Start chain from genesis state dump (+ validation)
~~* Historical staking data for IBC see https://github.com/cosmos/cosmos-sdk/blob/v0.42.5/x/ibc/core/02-client/types/expected_keepers.go#L11~~
~~* StakingAdapter implementation~~
~~* Add/ remove stake ? What other  commands/ queries do we need~~
~~* Where do we store Validator meta data (moniker, ...) / ~~
~~* Edit validator meta data message/ command~~

## Puzzle
* How do we edit/set the Engagement group in genesis?
~~* Do we need an admin for the mixer contract?~~

**Comment by ethanfrey** [comment]
This #49 and #50 are all about dump-state-and-restart scenario.

This would be good to have before mainnet, although I would prefer x/upgrade generally (and we could x/upgrade to a new version that supports this if needed).

Could you make one issue that explains all requirements for dump-state-and-restart and close all these (and link them to the new issue). These are old, and a bit lost in the pile.

**Comment by alpe** [comment]
Closing this in favour of #49 + #50
