### ISSUE TITLE
PoE Genesis Validation

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#61]
Fail fast when validating the genesis file. 
Prevent:
-[ ] duplicate pubkeys in gentx (poe)
-[ ] duplicate pinned contracts (twasm)
-[ ] code_ids not existing for pinned contract (twasm)
-[ ] contract address not existing for privileged contracts (twasm)

To validate a genesis.json each module's [ValidateGenesis](https://github.com/confio/tgrade/blob/v0.6.0-rc2/x/poe/module.go#L64) is called with the data only under the modules name. You can work with the GenesisState types in the modules. For PoE validation is in https://github.com/confio/tgrade/blob/v0.6.0-rc2/x/poe/types/genesis.go#L75 .
Common practice is to use/ create `ValidateBasic() error` methods and fail with the first issue.

**Comment by ethanfrey** [comment]
Let's do some validation before the public testnet.
Since we don't currently use any contracts in genesis besides the ones we create in PoE, I would only focus on issues like duplicate pub keys and the like, not the code/pinned validation.
