### ISSUE TITLE
Do we need a Max gas setting for external/ internal messages

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#71]
With the global fee module we have some protection agains low fee messages spamming the system. 
But gas is not tight to fees so that an attacker could call a malicious contract with super hight gas settings but low fee.

**Comment by ethanfrey** [comment]
If we need to make any changes, these should be in wasmd.
I would create an issue in wasmd if still desired, and close this issue. O just close it.

**Comment by alpe** [comment]
Closing this now as with the globalfee handler we have gas and fees tight. wasmd ante handler takes care of a max gas.
